services:
  backend:
    build: ./backend
    environment:
      - NINA_NJAA_BASIC_AUTH_USER=${NINA_NJAA_BASIC_AUTH_USER:-admin}
      - NINA_NJAA_BASIC_AUTH_PASS=${NINA_NJAA_BASIC_AUTH_PASS:-password}
      - NINA_NJAA_DB_PATH=/app/db/recipes.db
      - NINA_NJAA_OPENAI_API_KEY=${NINA_NJAA_OPENAI_API_KEY}
      - NINA_NJAA_JWT_SECRET_KEY=${NINA_NJAA_JWT_SECRET_KEY}
    volumes:
      - ./db:/app/db
    networks:
      - app-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - static:/static
    networks:
      - app-net

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html
    depends_on:
      frontend:
        condition: service_completed_successfully
      backend:
        condition: service_started
    networks:
      - app-net
    restart: unless-stopped

volumes:
  static:

networks:
  app-net:
    driver: bridge
