services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/nina-njaa:cached
    command: sleep infinity
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
